/**
 * postbuild.mjs — Patches the Nitro-generated Cloudflare Worker entry
 * to intercept /api/* requests before the SSR catch-all.
 *
 * The @lovable.dev/vite-tanstack-config build ignores both:
 *   1. The custom server.ts entry (not compiled into the SSR bundle)
 *   2. Nitro server/ directory (scanDirs not passed through)
 *
 * This script injects API routing into the Cloudflare handler's fetch hook
 * so that /api/auth/*, /api/questions, /api/call, /api/chat are handled
 * by the auth handler and API handlers BEFORE reaching the TanStack Start
 * SSR renderer (which would return a 404 HTML page for unknown routes).
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const indexPath = resolve(__dirname, '..', '.output', 'server', 'index.mjs');

let code = readFileSync(indexPath, 'utf-8');

// ── 1. Find the Cloudflare handler's fetch hook and make it async + add API routing ──
//
// Original (generated by Nitro):
//   var cloudflare_module_default = createHandler({ fetch(cfRequest, env, context, url) {
//       if (env.ASSETS && isPublicAssetURL(url.pathname)) return env.ASSETS.fetch(cfRequest);
//   } });
//
// We replace it with a version that also intercepts /api/* paths.

const originalHandler = `createHandler({ fetch(cfRequest, env, context, url) {
\tif (env.ASSETS && isPublicAssetURL(url.pathname)) return env.ASSETS.fetch(cfRequest);
} })`;

const patchedHandler = `createHandler({ async fetch(cfRequest, env, context, url) {
\tif (env.ASSETS && isPublicAssetURL(url.pathname)) return env.ASSETS.fetch(cfRequest);
\t/* ── BEGIN postbuild API routing patch ── */
\tif (url.pathname.startsWith("/api/")) {
\t\ttry {
\t\t\tconst ssrService = services["ssr"];
\t\t\tif (!ssrService._apiMod) {
\t\t\t\tssrService._apiMod = import("./_ssr/ssr.mjs").then(m => m._apiHandlers);
\t\t\t}
\t\t\tconst api = await ssrService._apiMod;
\t\t\tif (api) {
\t\t\t\tconst res = await api(cfRequest, url);
\t\t\t\tif (res) return res;
\t\t\t}
\t\t} catch(e) { console.error("[API patch] error:", e); }
\t}
\t/* ── END postbuild API routing patch ── */
} })`;

if (code.includes(originalHandler)) {
  code = code.replace(originalHandler, patchedHandler);
  console.log('[postbuild] ✓ Patched Cloudflare handler fetch hook in index.mjs');
} else {
  // Try a more flexible match
  const flexPattern = /createHandler\(\{\s*fetch\(cfRequest,\s*env,\s*context,\s*url\)\s*\{[^}]*isPublicAssetURL[^}]*\}\s*\}\)/s;
  if (flexPattern.test(code)) {
    code = code.replace(flexPattern, patchedHandler);
    console.log('[postbuild] ✓ Patched Cloudflare handler fetch hook in index.mjs (flex match)');
  } else {
    console.error('[postbuild] ✗ Could not find Cloudflare handler pattern in index.mjs');
    console.error('[postbuild]   The Nitro output format may have changed. Manual fix required.');
    process.exit(1);
  }
}

writeFileSync(indexPath, code, 'utf-8');

// ── 2. Patch the SSR entry to export the API handlers ──
//
// We append an _apiHandlers export to ssr.mjs that the index.mjs patch calls.
// This lazily imports auth.ts and api-handlers.ts and routes requests.

const ssrPath = resolve(__dirname, '..', '.output', 'server', '_ssr', 'ssr.mjs');
let ssrCode = readFileSync(ssrPath, 'utf-8');

const apiHandlerCode = `
/* ── BEGIN postbuild API handlers ── */
var _betterAuthModule;
async function _getAuth() {
  if (!_betterAuthModule) {
    // Dynamic import of better-auth and dependencies
    // These are resolved at build time by Nitro's bundler
    const { betterAuth } = await import("better-auth");
    const { LibsqlDialect } = await import("@libsql/kysely-libsql");
    const { createClient } = await import("@libsql/client");

    function _getEnv(key) {
      if (typeof globalThis.__env__ !== "undefined" && globalThis.__env__[key]) return String(globalThis.__env__[key]);
      if (typeof process !== "undefined" && process.env && process.env[key]) return String(process.env[key]);
      return "";
    }

    const secret = _getEnv("BETTER_AUTH_SECRET") || "interviewmate_secret_key_32bytes_minimum_length_required";
    const envUrl = _getEnv("BETTER_AUTH_URL");
    const baseURL = envUrl || "https://interviewmate.shivamkareliya11.workers.dev";
    const clientId = (_getEnv("GOOGLE_CLIENT_ID") || _getEnv("VITE_GOOGLE_CLIENT_ID")).trim();
    const clientSecret = (_getEnv("GOOGLE_CLIENT_SECRET") || _getEnv("VITE_GOOGLE_CLIENT_SECRET")).trim();

    try {
      const dialect = new LibsqlDialect({ client: createClient({ url: "file:sqlite.db" }) });
      _betterAuthModule = betterAuth({
        database: dialect,
        secret,
        baseURL,
        emailAndPassword: { enabled: true },
        socialProviders: { google: { clientId, clientSecret } },
        account: { accountLinking: { enabled: true, trustedProviders: ["google"] } }
      });
    } catch(e) {
      console.error("[postbuild auth] Failed to init betterAuth:", e);
      _betterAuthModule = { handler: async () => new Response(JSON.stringify({error:"Auth misconfigured"}), {status:500, headers:{"content-type":"application/json"}}) };
    }
  }
  return _betterAuthModule;
}

async function _apiHandlers(request, url) {
  // Auth routes
  if (url.pathname.startsWith("/api/auth")) {
    try {
      const authInst = await _getAuth();
      return await authInst.handler(request);
    } catch(e) {
      if (e?.message?.includes("Invalid Base64")) {
        return new Response(JSON.stringify({session:null,user:null}), {status:200, headers:{"content-type":"application/json"}});
      }
      console.error("[API auth] error:", e);
      return new Response(JSON.stringify({error:"Auth error"}), {status:500, headers:{"content-type":"application/json"}});
    }
  }

  // Other API routes (POST only)
  if (request.method === "POST") {
    try {
      const body = await request.clone().json();
      const { messages, jsonMode } = body || {};
      
      function _groqApiKey() { return _getEnvFromGlobal("GROQ_API_KEY"); }
      function _getEnvFromGlobal(k) {
        if (typeof globalThis.__env__ !== "undefined" && globalThis.__env__[k]) return String(globalThis.__env__[k]);
        if (typeof process !== "undefined" && process.env && process.env[k]) return String(process.env[k]);
        return "";
      }

      if (url.pathname === "/api/questions" || url.pathname === "/api/call" || url.pathname === "/api/chat") {
        const apiKey = _groqApiKey();
        const baseUrl = _getEnvFromGlobal("GROQ_API_URL") || _getEnvFromGlobal("VITE_GROQ_API_URL") || "https://api.groq.com/openai/v1";
        const model = _getEnvFromGlobal("GROQ_MODEL") || _getEnvFromGlobal("VITE_GROQ_MODEL") || "llama-3.1-8b-instant";
        const isChat = url.pathname === "/api/chat";
        const isJsonMode = url.pathname !== "/api/chat" ? true : false;

        if (!apiKey || !apiKey.startsWith("gsk_")) {
          // Fallback to pollinations
          const fallbackRes = await fetch("https://text.pollinations.ai/", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ messages, model: "openai" }),
          });
          if (fallbackRes.ok) {
            const text = await fallbackRes.text();
            if (isChat) return new Response(text);
            if (text && text.length > 10) {
              const jsonMatch = text.match(/\\{[\\s\\S]*\\}/);
              if (jsonMatch) return new Response(jsonMatch[0], { headers: { "Content-Type": "application/json" } });
              return new Response(text.trim(), { headers: { "Content-Type": "application/json" } });
            }
          }
          return new Response(JSON.stringify({ error: "No valid GROQ_API_KEY found and fallback failed." }), { status: 500, headers: { "Content-Type": "application/json" } });
        }

        const groqBody = { model, messages, temperature: 0.3 };
        if (isChat) groqBody.stream = true;
        else groqBody.response_format = { type: "json_object" };

        const response = await fetch(baseUrl + "/chat/completions", {
          method: "POST",
          headers: { "Content-Type": "application/json", "Authorization": "Bearer " + apiKey },
          body: JSON.stringify(groqBody),
        });

        if (!response.ok) {
          const errorText = await response.text();
          return new Response(isChat ? "Groq API Error: " + errorText : JSON.stringify({ error: "Groq API Error: " + errorText }), { status: response.status, headers: isChat ? {} : { "Content-Type": "application/json" } });
        }

        if (isChat) {
          return new Response(response.body, { headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-cache", "Connection": "keep-alive" } });
        }

        const data = await response.json();
        const content = data.choices?.[0]?.message?.content;
        if (content) {
          const jsonMatch = content.match(/\\{[\\s\\S]*\\}/);
          if (jsonMatch) return new Response(jsonMatch[0], { headers: { "Content-Type": "application/json" } });
          return new Response(content.trim(), { headers: { "Content-Type": "application/json" } });
        }
        return new Response(JSON.stringify({ error: "Empty response from Groq" }), { status: 500, headers: { "Content-Type": "application/json" } });
      }
    } catch(e) {
      console.error("[API handler] error:", e);
      return new Response(JSON.stringify({ error: "Internal Server Error" }), { status: 500, headers: { "Content-Type": "application/json" } });
    }
  }

  return null; // Not an API route we handle — fall through to SSR
}

export { _apiHandlers };
/* ── END postbuild API handlers ── */
`;

ssrCode += apiHandlerCode;
writeFileSync(ssrPath, ssrCode, 'utf-8');

console.log('[postbuild] ✓ Appended API handlers to ssr.mjs');
console.log('[postbuild] ✓ Done! API routes will now be intercepted before SSR.');
