/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ApiCallRouteImport } from './routes/api/call'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiQuestionsRouteImport } from './routes/api/questions'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedUserAnalyticsRouteImport } from './routes/_authenticated/user/analytics'
import { Route as AuthenticatedUserBookmarksRouteImport } from './routes/_authenticated/user/bookmarks'
import { Route as AuthenticatedUserCompaniesRouteImport } from './routes/_authenticated/user/companies'
import { Route as AuthenticatedUserDashboardRouteImport } from './routes/_authenticated/user/dashboard'
import { Route as AuthenticatedUserHistoryRouteImport } from './routes/_authenticated/user/history'
import { Route as AuthenticatedUserMockinterviewRouteImport } from './routes/_authenticated/user/mockinterview'
import { Route as AuthenticatedUserPracticeRouteImport } from './routes/_authenticated/user/practice'
import { Route as AuthenticatedUserResumeRouteImport } from './routes/_authenticated/user/resume'
import { Route as AuthenticatedUserSettingsRouteImport } from './routes/_authenticated/user/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedUserCompaniesCompanyIdRouteImport } from './routes/_authenticated/user/companies.$companyId'
import { Route as AuthenticatedUserSessionSessionIdRouteImport } from './routes/_authenticated/user/session/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallRoute = ApiCallRouteImport.update({
  id: '/api/call',
  path: '/api/call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestionsRoute = ApiQuestionsRouteImport.update({
  id: '/api/questions',
  path: '/api/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserAnalyticsRoute =
  AuthenticatedUserAnalyticsRouteImport.update({
    id: '/user/analytics',
    path: '/user/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserBookmarksRoute =
  AuthenticatedUserBookmarksRouteImport.update({
    id: '/user/bookmarks',
    path: '/user/bookmarks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserCompaniesRoute =
  AuthenticatedUserCompaniesRouteImport.update({
    id: '/user/companies',
    path: '/user/companies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserDashboardRoute =
  AuthenticatedUserDashboardRouteImport.update({
    id: '/user/dashboard',
    path: '/user/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserHistoryRoute =
  AuthenticatedUserHistoryRouteImport.update({
    id: '/user/history',
    path: '/user/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserMockinterviewRoute =
  AuthenticatedUserMockinterviewRouteImport.update({
    id: '/user/mockinterview',
    path: '/user/mockinterview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserPracticeRoute =
  AuthenticatedUserPracticeRouteImport.update({
    id: '/user/practice',
    path: '/user/practice',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserResumeRoute = AuthenticatedUserResumeRouteImport.update({
  id: '/user/resume',
  path: '/user/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserSettingsRoute =
  AuthenticatedUserSettingsRouteImport.update({
    id: '/user/settings',
    path: '/user/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserCompaniesCompanyIdRoute =
  AuthenticatedUserCompaniesCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AuthenticatedUserCompaniesRoute,
  } as any)
const AuthenticatedUserSessionSessionIdRoute =
  AuthenticatedUserSessionSessionIdRouteImport.update({
    id: '/user/session/$sessionId',
    path: '/user/session/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/call': typeof ApiCallRoute
  '/api/chat': typeof ApiChatRoute
  '/api/questions': typeof ApiQuestionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/user/analytics': typeof AuthenticatedUserAnalyticsRoute
  '/user/bookmarks': typeof AuthenticatedUserBookmarksRoute
  '/user/companies': typeof AuthenticatedUserCompaniesRouteWithChildren
  '/user/dashboard': typeof AuthenticatedUserDashboardRoute
  '/user/history': typeof AuthenticatedUserHistoryRoute
  '/user/mockinterview': typeof AuthenticatedUserMockinterviewRoute
  '/user/practice': typeof AuthenticatedUserPracticeRoute
  '/user/resume': typeof AuthenticatedUserResumeRoute
  '/user/settings': typeof AuthenticatedUserSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/user/companies/$companyId': typeof AuthenticatedUserCompaniesCompanyIdRoute
  '/user/session/$sessionId': typeof AuthenticatedUserSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/call': typeof ApiCallRoute
  '/api/chat': typeof ApiChatRoute
  '/api/questions': typeof ApiQuestionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/user/analytics': typeof AuthenticatedUserAnalyticsRoute
  '/user/bookmarks': typeof AuthenticatedUserBookmarksRoute
  '/user/companies': typeof AuthenticatedUserCompaniesRouteWithChildren
  '/user/dashboard': typeof AuthenticatedUserDashboardRoute
  '/user/history': typeof AuthenticatedUserHistoryRoute
  '/user/mockinterview': typeof AuthenticatedUserMockinterviewRoute
  '/user/practice': typeof AuthenticatedUserPracticeRoute
  '/user/resume': typeof AuthenticatedUserResumeRoute
  '/user/settings': typeof AuthenticatedUserSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/user/companies/$companyId': typeof AuthenticatedUserCompaniesCompanyIdRoute
  '/user/session/$sessionId': typeof AuthenticatedUserSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/call': typeof ApiCallRoute
  '/api/chat': typeof ApiChatRoute
  '/api/questions': typeof ApiQuestionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/user/analytics': typeof AuthenticatedUserAnalyticsRoute
  '/_authenticated/user/bookmarks': typeof AuthenticatedUserBookmarksRoute
  '/_authenticated/user/companies': typeof AuthenticatedUserCompaniesRouteWithChildren
  '/_authenticated/user/dashboard': typeof AuthenticatedUserDashboardRoute
  '/_authenticated/user/history': typeof AuthenticatedUserHistoryRoute
  '/_authenticated/user/mockinterview': typeof AuthenticatedUserMockinterviewRoute
  '/_authenticated/user/practice': typeof AuthenticatedUserPracticeRoute
  '/_authenticated/user/resume': typeof AuthenticatedUserResumeRoute
  '/_authenticated/user/settings': typeof AuthenticatedUserSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/user/companies/$companyId': typeof AuthenticatedUserCompaniesCompanyIdRoute
  '/_authenticated/user/session/$sessionId': typeof AuthenticatedUserSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api/call'
    | '/api/chat'
    | '/api/questions'
    | '/auth/callback'
    | '/user/analytics'
    | '/user/bookmarks'
    | '/user/companies'
    | '/user/dashboard'
    | '/user/history'
    | '/user/mockinterview'
    | '/user/practice'
    | '/user/resume'
    | '/user/settings'
    | '/api/auth/$'
    | '/user/companies/$companyId'
    | '/user/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api/call'
    | '/api/chat'
    | '/api/questions'
    | '/auth/callback'
    | '/user/analytics'
    | '/user/bookmarks'
    | '/user/companies'
    | '/user/dashboard'
    | '/user/history'
    | '/user/mockinterview'
    | '/user/practice'
    | '/user/resume'
    | '/user/settings'
    | '/api/auth/$'
    | '/user/companies/$companyId'
    | '/user/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/sign-up'
    | '/api/call'
    | '/api/chat'
    | '/api/questions'
    | '/auth/callback'
    | '/_authenticated/user/analytics'
    | '/_authenticated/user/bookmarks'
    | '/_authenticated/user/companies'
    | '/_authenticated/user/dashboard'
    | '/_authenticated/user/history'
    | '/_authenticated/user/mockinterview'
    | '/_authenticated/user/practice'
    | '/_authenticated/user/resume'
    | '/_authenticated/user/settings'
    | '/api/auth/$'
    | '/_authenticated/user/companies/$companyId'
    | '/_authenticated/user/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiCallRoute: typeof ApiCallRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiQuestionsRoute: typeof ApiQuestionsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/call': {
      id: '/api/call'
      path: '/api/call'
      fullPath: '/api/call'
      preLoaderRoute: typeof ApiCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/questions': {
      id: '/api/questions'
      path: '/api/questions'
      fullPath: '/api/questions'
      preLoaderRoute: typeof ApiQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/user/analytics': {
      id: '/_authenticated/user/analytics'
      path: '/user/analytics'
      fullPath: '/user/analytics'
      preLoaderRoute: typeof AuthenticatedUserAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/bookmarks': {
      id: '/_authenticated/user/bookmarks'
      path: '/user/bookmarks'
      fullPath: '/user/bookmarks'
      preLoaderRoute: typeof AuthenticatedUserBookmarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/companies': {
      id: '/_authenticated/user/companies'
      path: '/user/companies'
      fullPath: '/user/companies'
      preLoaderRoute: typeof AuthenticatedUserCompaniesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/dashboard': {
      id: '/_authenticated/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof AuthenticatedUserDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/history': {
      id: '/_authenticated/user/history'
      path: '/user/history'
      fullPath: '/user/history'
      preLoaderRoute: typeof AuthenticatedUserHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/mockinterview': {
      id: '/_authenticated/user/mockinterview'
      path: '/user/mockinterview'
      fullPath: '/user/mockinterview'
      preLoaderRoute: typeof AuthenticatedUserMockinterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/practice': {
      id: '/_authenticated/user/practice'
      path: '/user/practice'
      fullPath: '/user/practice'
      preLoaderRoute: typeof AuthenticatedUserPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/resume': {
      id: '/_authenticated/user/resume'
      path: '/user/resume'
      fullPath: '/user/resume'
      preLoaderRoute: typeof AuthenticatedUserResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/settings': {
      id: '/_authenticated/user/settings'
      path: '/user/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof AuthenticatedUserSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/user/companies/$companyId': {
      id: '/_authenticated/user/companies/$companyId'
      path: '/$companyId'
      fullPath: '/user/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedUserCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedUserCompaniesRoute
    }
    '/_authenticated/user/session/$sessionId': {
      id: '/_authenticated/user/session/$sessionId'
      path: '/user/session/$sessionId'
      fullPath: '/user/session/$sessionId'
      preLoaderRoute: typeof AuthenticatedUserSessionSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedUserCompaniesRouteChildren {
  AuthenticatedUserCompaniesCompanyIdRoute: typeof AuthenticatedUserCompaniesCompanyIdRoute
}

const AuthenticatedUserCompaniesRouteChildren: AuthenticatedUserCompaniesRouteChildren =
  {
    AuthenticatedUserCompaniesCompanyIdRoute:
      AuthenticatedUserCompaniesCompanyIdRoute,
  }

const AuthenticatedUserCompaniesRouteWithChildren =
  AuthenticatedUserCompaniesRoute._addFileChildren(
    AuthenticatedUserCompaniesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedUserAnalyticsRoute: typeof AuthenticatedUserAnalyticsRoute
  AuthenticatedUserBookmarksRoute: typeof AuthenticatedUserBookmarksRoute
  AuthenticatedUserCompaniesRoute: typeof AuthenticatedUserCompaniesRouteWithChildren
  AuthenticatedUserDashboardRoute: typeof AuthenticatedUserDashboardRoute
  AuthenticatedUserHistoryRoute: typeof AuthenticatedUserHistoryRoute
  AuthenticatedUserMockinterviewRoute: typeof AuthenticatedUserMockinterviewRoute
  AuthenticatedUserPracticeRoute: typeof AuthenticatedUserPracticeRoute
  AuthenticatedUserResumeRoute: typeof AuthenticatedUserResumeRoute
  AuthenticatedUserSettingsRoute: typeof AuthenticatedUserSettingsRoute
  AuthenticatedUserSessionSessionIdRoute: typeof AuthenticatedUserSessionSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedUserAnalyticsRoute: AuthenticatedUserAnalyticsRoute,
  AuthenticatedUserBookmarksRoute: AuthenticatedUserBookmarksRoute,
  AuthenticatedUserCompaniesRoute: AuthenticatedUserCompaniesRouteWithChildren,
  AuthenticatedUserDashboardRoute: AuthenticatedUserDashboardRoute,
  AuthenticatedUserHistoryRoute: AuthenticatedUserHistoryRoute,
  AuthenticatedUserMockinterviewRoute: AuthenticatedUserMockinterviewRoute,
  AuthenticatedUserPracticeRoute: AuthenticatedUserPracticeRoute,
  AuthenticatedUserResumeRoute: AuthenticatedUserResumeRoute,
  AuthenticatedUserSettingsRoute: AuthenticatedUserSettingsRoute,
  AuthenticatedUserSessionSessionIdRoute:
    AuthenticatedUserSessionSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiCallRoute: ApiCallRoute,
  ApiChatRoute: ApiChatRoute,
  ApiQuestionsRoute: ApiQuestionsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
